Project TEST{
database_type: 'Oracle'
Note: '''
    # TEST Schedule Database
'''
}

Table COURSE [note: '課程'] {
	COURSE_ID         NUMBER(20)         [pk, not null, note: '主檔流水號']
	COURSE_NAME       VARCHAR2 (16 CHAR) [not null, note: '課程名稱']
	COURSE_TYPE       NUMBER(20)         [not null, note: '關聯到：課程類型', ref: > TYPE.TYPE]
	COURSE_TYPE_CODE  NUMBER(20)         [not null, note: '關聯到：課程類型', ref: > TYPE.TYPE_CODE]
	CREATE_TIME       DATE               [not null, note: '建立時間']
}

Table TYPE [note: '類型'] {
	TYPE              NUMBER(20)         [pk, not null, note: '類型']
	TYPE_CODE         VARCHAR2 (16 CHAR) [pk, not null, note: '類型代碼']
	TYPE_NAME         VARCHAR2 (16 CHAR) [not null, note: '類型名稱']
	CREATE_TIME       DATE               [not null, note: '建立時間']
}

Table STUDENT [note: '學生'] {
	STUDENT_ID        NUMBER(20)         [pk, not null, note: '主檔流水號']
	STUDENT_NAME      VARCHAR2 (16 CHAR) [not null, note: '學生姓名']
	CREATE_TIME       DATE               [not null, note: '建立時間']
}

Table COURSE_STUDENT [note: '課程學生'] {
	COURSE_STUDENT_ID NUMBER(20)         [pk, not null, note: '主檔流水號']
	COURSE_ID         NUMBER(20)         [not null, note: '課程ID', ref: > COURSE.COURSE_ID]
	STUDENT_ID        NUMBER(20)         [not null, note: '學生ID', ref: > STUDENT.STUDENT_ID]
	CREATE_TIME       DATE               [not null, note: '建立時間']
}

