Project TEST{
database_type: 'Oracle'
Note: '''
    # TEST Schedule Database
'''
}

Table COURSE [note: '課程'] {
	COURSE_ID         NUMBER(20)         [pk, not null, note: '主檔流水號']
	COURSE_NAME       VARCHAR2 (16 CHAR) [not null, note: '課程名稱']
	COURSE_TYPE_ID    NUMBER(20)         [not null, note: '關聯到：課程類型', ref: > COURSE_TYPE.COURSE_TYPE_ID]
	CREATE_TIME       DATE               [not null, note: '建立時間']
}

Table COURSE_TYPE [note: '課程類型'] {
	COURSE_TYPE_ID    NUMBER(20)         [pk, not null, note: '主檔流水號']
	COURSE_TYPE_NAME  VARCHAR2 (16 CHAR) [not null, note: '課程類型名稱']
	CREATE_TIME       DATE               [not null, note: '建立時間']
}

Table STUDENT [note: '學生'] {
	STUDENT_ID        NUMBER(20)         [pk, not null, note: '主檔流水號']
	STUDENT_NAME      VARCHAR2 (16 CHAR) [not null, note: '學生姓名']
	CREATE_TIME       DATE               [not null, note: '建立時間']
}

Table COURSE_STUDENT [note: '課程學生'] {
	COURSE_STUDENT_ID NUMBER(20)         [pk, not null, note: '主檔流水號']
	COURSE_ID         NUMBER(20)         [not null, note: '課程ID', ref: > COURSE.COURSE_ID]
	STUDENT_ID        NUMBER(20)         [not null, note: '學生ID', ref: > STUDENT.STUDENT_ID]
	CREATE_TIME       DATE               [not null, note: '建立時間']
}

Table EXAM [note: '測驗'] {
	EXAM_TYPE         NUMBER(20)         [pk, not null, note: '測驗類型']
	EXAM_TYPE_CODE    VARCHAR2 (16 CHAR) [pk, not null, note: '測驗類型代碼']
	CREATE_TIME       DATE               [not null, note: '建立時間']
}

Table STUDENT_EXAM [note: '學生測驗'] {
	STUDENT_EXAM_ID   NUMBER(20)         [pk, not null, note: '主檔流水號']
	STUDENT_ID        NUMBER(20)         [not null, note: '學生ID', ref: > STUDENT.STUDENT_ID]
	EXAM_TYPE         NUMBER(20)         [not null, note: '測驗類型', ref: > EXAM.EXAM_TYPE]
	EXAM_TYPE_CODE    VARCHAR2 (16 CHAR) [not null, note: '測驗代碼', ref: > EXAM.EXAM_TYPE_CODE]
	CREATE_TIME       DATE               [not null, note: '建立時間']
}

